document.querySelector('#play-btn1').addEventListener('click',function(){
    window.location.href="First-game.html";
});
document.querySelector('#play-btn2').addEventListener('click',function(){
    window.location.href="Second-game.html";
});
document.querySelector('#play-btn3').addEventListener('click',function(){
    window.location.href="Third-game.html";
});
document.querySelector('#play-btn4').addEventListener('click',function(){
    window.location.href="Fourth-game.html";
});
document.querySelector('#play-btn5').addEventListener('click',function(){
    window.location.href="Fifth-game.html";
});
document.querySelector('#play-btn6').addEventListener('click',function(){
    window.location.href="Sixth-game.html";
});
document.querySelector('#play-btn7').addEventListener('click',function(){
    window.location.href="Seventh-game.html";
});
document.querySelector('#play-btn8').addEventListener('click',function(){
    window.location.href="Eighth-game.html";
});
document.querySelector('#play-btn9').addEventListener('click',function(){
    window.location.href="Ninth-game.html";
});